### ISSUE TITLE
Suche mit Apostroph fehlerhaft

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#102]
Gemeldet von: LT

Beispiele:

Year's work in critical an cultural theory --> die Zeitschrift wird nicht gefunden

work in critical an cultural theory --> so wird die Zeitschrift gefunden

Blackwood's Edinburgh magazin --> die Zeitschrift wird nicht gefunden

Edinburgh magazine --> so wird die Zeitschrift gefunden

**Comment by msievers** [comment]
Duplicate of #90

**Comment by msievers** [comment]
Fixed with latest index changes.
