### ISSUE TITLE
DBIS Links auf den Katalog sind defekt

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#11]
DBIS verlinkt auf den Katalog mit einer alten Syntax. Da es sich hier um sehr viele Links handelt, ist zu prüfen ob wir das doch umleiten können, oder ob alle DBIS Links händisch aktualisiert werden müssen.

Beispiele
http://rzblx10.uni-regensburg.de/dbinfo/detail.php?bib_id=ub_pb&colors=&ocolors=&lett=c&tid=1&titel_id=8901
http://rzblx10.uni-regensburg.de/dbinfo/detail.php?bib_id=ub_pb&colors=&ocolors=&lett=c&tid=1&titel_id=9089
http://rzblx10.uni-regensburg.de/dbinfo/detail.php?bib_id=ub_pb&colors=&ocolors=&lett=c&tid=1&titel_id=8263

ansonsten alle Titel mit Links auf unseren Katalog unter
http://rzblx10.uni-regensburg.de/dbinfo/dbliste.php?bib_id=ub_pb&lett=c&collid=EB

**Comment by msievers** [comment]
Das Problem bei den DBIS Links und wahrscheinlich auch bei vielen anderen Links ist, dass der Scope vom Querystring in die URL gewandert ist.

**Comment by msievers** [comment]
Ich hab den Code auf katalog-test deployed und dort funktioniert alles.
