### ISSUE TITLE
Man kann im Feld Selektionskennzeichen nicht suchen

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#12]
Wird benötigt für #11 

Beispiel: https://katalog.ub.uni-paderborn.de/local/searches?search_request=%7B%22queries%22%3A%5B%7B%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_operator%22%3A%22AND%22%2C%22fields%22%3A%5B%22selection_code%22%5D%2C%22query%22%3A%22zdb-2-sbe%22%7D%5D%2C%22sort%22%3A%5B%7B%22field%22%3A%22_score%22%7D%5D%7D

**Comment by msievers** [comment]
Im Augenblick gehört das Feld `selection_code` zu den nicht analysierten Feldern, was dazu führt, dass es nur **exakt** so gefunden werden kann, wie eingegeben. Dies ist aber nicht das, was der Benutzer an dieser Stelle erwartet.

**Comment by msievers** [comment]
Lösungsvorschlag

Das Feld `selection_code` *normal* Analysieren wie alle anderen Felder auch. Dazu muss es lediglich aus der Liste nicht analyiserter Felder entfernt werden ([siehe Code](https://github.com/ubpb/metacrunch-ubpb/blob/master/lib/metacrunch/ubpb/cli/load_index.rb#L41))

**Comment by msievers** [comment]
Anstatt das Feld mit Hilfe des `default` Analyzers zu analysieren wird für dieses Feld der neue geschaffene `minimal` Analyzer benutzt.
