### ISSUE TITLE
Übersetzung für Sortierkriterium fehlt

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#25]
https://katalog.ub.uni-paderborn.de/local/searches?search_request={%22from%22%3A0%2C%22queries%22%3A[{%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_operator%22%3A%22AND%22%2C%22fields%22%3A[%22superorder%22]%2C%22query%22%3A%22HT001236095%22}]%2C%22size%22%3A25%2C%22sort%22%3A[{%22field%22%3A%22volume_count_sort%22%2C%22order%22%3A%22asc%22}]}

**Comment by msievers** [comment]
Das kann doch gar nicht sein, dass hattest du doch auf volume_count_sort2 geändert @renspr

**Comment by msievers** [comment]
Die Übersetzung fehlt, weil die im Translationfile von `volume_count_sort` in ' volume_count_sort2` umbenannt wurde, weil `volume_count_sort` ja nicht so funktioniert hat wie erhofft.

**Comment by msievers** [comment]
Ahhhh, der hier ist das Problem

https://github.com/ubpb/katalog_ubpb/blob/44da9536535f8f26735560f07ddd5385dca17027/app/helpers/link_helper.rb#L23

Der Linkhelüer benutzt noch `volume_count_sort` ...
