### ISSUE TITLE
Login / Redirect Problematik

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#27]
Die Anmeldemaske "unterbricht" z.B. Funktionen wie "Magazinbestellung", "Vormerken" oder auch "Nutzer möchte einen Titel auf Merkliste setzen, ist aber nicht angemeldet. Klickt dann auf Login, landet dann aber im Benutzerkonto und verliert den Suchkontext". 

Gibt es eine allgemein funktionierende Lösung?

**Comment by msievers** [comment]
Magzinbestellung leitet ihn zurück zum Referer, hab ich gerade vorhin erst gehabt.

**Comment by msievers** [comment]
Der Mechanismus zum `redirect_back_to ...` existiert ja grundsätzlich. Vielleicht wird der einfach an der einen oder anderen Stelle wo's sinnvoll wäre (noch) nicht verwendet.

**Comment by renspr** [comment]
Das Szenario "Nutzer möchte einen Titel auf Merkliste setzen, ist aber nicht angemeldet. Klickt dann auf Login, landet dann aber im Benutzerkonto und verliert den Suchkontext" lässt sich damit nicht in den Griff bekommen.

Ich denke darüber nach, den Login Button generell wieder mit dem return_path auzustatten und dann auf der Anmeldemaske drei Knöpfe zu machen: "Login und weiter zum Benutzerkonto", "Login und zurück" und "Abbrechen"  (Abbrechen führt ebenfalls zurück). Dann könnten wir uns alle implizieren regeln sparen.

**Comment by msievers** [comment]
Konkret für die Merklisten können wir das auch auf die schnelle erstmal in der `RecordActions` Component "reparieren".
