### ISSUE TITLE
Der Punkt "Recherchieren" in der Breadcrumb führt aus dem Katalog raus

### ISSUE THREAD

**Issue by msievers** [ubpb/issues#29]
Frau Weimer hat gerade angemerkt, dass sie, wenn sie etwas gesucht hat und eine neue Suche anstoßen möchte, häufig oben in der Breadcrumb auf "Recherchieren" klickt, was sie jedoch aus dem Katalog heraus auf die UB Homepage bringt, wo aktuell ja gar kein Suchschlitz mehr existiert.

Sie fragt, ob wir "Recherchieren" im aktuellen Kontext streichen könnten um dadurch den Effekt "Ich will neu suchen, klicke auf Recherchieren, lande auf der UB Seite, muss klicken um auf den Katalog zu kommen" zu beseitigen.

**Comment by renspr** [comment]
In der Breadcrumb steht doch "Katalog" drin. Und "UB -> Recherchieren -> Katalog" ist nunmal der korrekte Pfad. Ich würde das so lassen wie es ist.
