### ISSUE TITLE
Phrasensuche geht nicht mehr

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#40]
Gemeldet von: LT

Die Phrasensuche funktioniert nicht mehr. Beispiel "Zeitschrift für Chemie" bringt  mit "Titel" 95 Treffer, u.a. auch "Zeitschrift für anorganische Chemie"

**Comment by renspr** [comment]
Kann ich nicht reproduzieren.

https://katalog.ub.uni-paderborn.de/local/searches?search_request=%7B%22queries%22%3A%5B%7B%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_operator%22%3A%22AND%22%2C%22query%22%3A%22+%5C%22Zeitschrift+f%C3%BCr+Chemie%5C%22%22%7D%5D%7D

Liefert genau 8 Treffer mit der Phrase im Titel.

**Comment by msievers** [comment]
Kann es auch nicht nachvollziehen. Treffermenge verhält sich wie erwartet, sowohl für alle Felder aus auch nur für Titel.
