### ISSUE TITLE
ISBN Suche defekt

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#41]
Bei dem Beispiel wird kein Treffer gefunden. Entfernt man die "-" wird der Titel gefunden.

https://katalog.ub.uni-paderborn.de/local/searches?search_request={"queries":[{"type":"query_string","fields":["isbn_search"],"query":"3-89721-426-1"}]}

**Comment by msievers** [comment]
Das Problem mit den ISBNs war kniffliger als gedacht. Das setzen von `catenate_all` im `ubpb_word_delemiter` Tokenfilter war leider nicht ausreichend. Der Grund hierfür ist bei ISBNs die Möglichkeit, sie an verschiedenen Stellen per Bindestrich zu trennen.

Wird eine ISBN nun in der Form "123-4567-89" indiziert, so landen folgende Tokens im Index `123`, `4567`, `89`, `123-4567-89`, `123456789`.

Sucht jetzt aber jemand nach `12-34567-89` so wird dies vom Tokenizer in die Tokens `12`, `34567`, `89`, `12-34567-89`, `123456789` zerlegt.

Das Problem ist nun der `default_operator` `AND` im `query_string`. Es gibt hier nämlich keinen Match wenn man die Tokens einer anders getrennten ISBN mit den Tokens im Index vergleicht, zumindest keinen wo ALLE Tokens des Queries mit Tokens im Index matchen.

Ich habe mich deshalb nun schweren Herzens dafür entschieden, für das Feld `isbn_search` einen eigenen Analyzer anzulegen, damit dieses Problem endlich vom Tisch ist. Dieser entfernt nun einfach alle `dashes` aus der eingabe und sorgt dafür, dass nur noch eine Version der ISBN im Index landet und dass Queries gegen dieses Feld auch nur eine ISBN ohne Bindestriche sein kann.

**Comment by msievers** [comment]
Da das Problem bei ISSNs mit Hoher Wahrscheinlichkeit genauso besteht, werde ich diesen Analyzer auch gleich noch mit für das ISSn Feld benutzen.

**Comment by msievers** [comment]
Bitte schließen sobald Daten geladen wurden.

**Comment by msievers** [comment]
Der neue Analyzer für die Felder ´isbn_search` and `issn` hat leider als Seiteneffekt zur Folge, dass ISBNs nun nicht mehr einfach in `_all` gefunden werden können, da Suchanfragen gegen `_all` durch die `default` Analyzer geschickt werden, welcher für ISBNs/ISSNs mit Bindestrichen andere Tokens erzeugt als der `isbn_analyzer`, welcher jedoch bei Suchen auschließlich für `isbn_search` bzw. ìssn` angewendet wird.

Als Workaround werden nun einfach die beiden Sonderfelder `isbn_search` und `issn` einem Query adapterseitig hinzugefügt, sobald erkannt wurde, dass es sich um eine Suche gegen `_all` handelt.

**Comment by renspr** [comment]
Gefixt mit Index katalog_20160318
