### ISSUE TITLE
Behandlung von Bindestrichen

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#42]
Gemeldet von: LT

Die Suche mit: Fussball-Training
bringt die gleiche Treffermenge wie mit: Fussball Training
(alle Felder 159, Titel 15)

Die Suche mit: Fussballtraining
bringt aber nur 41 bzw. 36 Treffer,

d.h. der Bindestrich wird wie ein Leerzeichen gewertet. Nach deutscher Rechtschreibung müsste er aber wie nicht vorhanden gewertet werden, also wie die zusammen geschriebene Schreibweise.

Könnte man im Katalog nicht beide Wertungen zulassen, also als Leerzeichen oder als zusammen geschrieben?

**Comment by msievers** [comment]
Sollte jetzt funktionieren. Suche im Titel nach `Fußball-Training` gibt 16 Treffer, `Fußball Training` gibt 15. Das legt nahe das bei der mit Bindestrich geschriebenen Variante der zusammengezogene Titel `Fußballtraining` ebenfalls gefunden wird.
