### ISSUE TITLE
Suche über alle Felder defekt

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#46]
Suche von "Kinder und Jugendbuch" findet in "Alle Felder" keine Treffer. Sucht man über "Titel" werden Titel "Kinder- und Jugendbuch" gefunden.

**Comment by renspr** [comment]
Das Problem scheint mit dem Stoppwort "und" zu tun zu haben. Gibt man "kinder jugendbuch" ein wird der Titel gefunden. bei "kinder und jugendbuch" nicht.

**Comment by renspr** [comment]
Mit Umstellung auf den Index katalog_20160209 scheint das Problem behoben. Die Frage ist, warum. @msievers

**Comment by msievers** [comment]
Das Problem scheint darauf zurückzuführen sein, dass es kurzfristig einen eigenen Analyzer für das Feld `isbn_search` gab und dass Suchen gegen `Alle Felder` im Adapter expandiert wurden zu Suchen gegen `_all` und `isbn_search`. Da im `isbn_analyzer` der `stopword` Tokenfilter gefehlt hat, konnte der resultierende Multifield-QueryStringQuery nicht positiv abgeschlossen werden. Siehe dazu folgende Umwandlungsschritte.

```
{
  "query_string" : {
     "fields" : ["_all", "isbn_search"],
     "query" : "kinder und jugendbuch",
     "default_operator": "AND"
  }
}

{
  "query_string" : {
     "fields" : ["_all", "isbn_search"],
     "query" : "kinder AND und AND jugendbuch"
  }
}

{
  "query_string" : {
     "query" : "(_all:kinder OR isbn_search:kinder) AND (_all:und OR isbn_search:und) AND (_all:jugendbuch OR isbn_search:jugendbuch)"
  }
}
```

Die mittlere AND verknüpfte OR Clause schlegt in diesem Fall immer fehl.

Das Problem konnte mit der Umstellung auf den aktuellsten Index gelöst werden, weil dort das Feld `isbn_search` wieder mit dem gleichen Default-Analyzer analysiert wird wie alle anderen Felder auch.
