### ISSUE TITLE
Nicht-deterministisches Verhalten von Mehr-Wort-Suchanfragen in PrimoCentral

### ISSUE THREAD

**Issue by msievers** [ubpb/issues#53]
Sucht man PrimoCentral nach mehreren Worten, kann es vorkommen, dass sich die Treffermenge irgendwann ab einem Wort vergrößert, anstatt weiter zu schrumpfen.

Beispiel:
* [goethe fast sprache](https://katalog.ub.upb.de/primo_central/searches?search_request=%7B%22queries%22%3A%5B%7B%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_field%22%3Anull%2C%22default_operator%22%3A%22AND%22%2C%22fields%22%3A%5B%22any%22%5D%2C%22query%22%3A%22goethe+faust+sprache%22%7D%5D%2C%22sort%22%3A%5B%7B%22field%22%3A%22rank%22%7D%5D%7D) (73 Treffer)
* [goethe faust sprache leben](https://katalog.ub.upb.de/primo_central/searches?search_request=%7B%22queries%22%3A%5B%7B%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_field%22%3Anull%2C%22default_operator%22%3A%22AND%22%2C%22fields%22%3A%5B%22any%22%5D%2C%22query%22%3A%22goethe+faust+sprache+leben%22%7D%5D%2C%22sort%22%3A%5B%7B%22field%22%3A%22rank%22%7D%5D%7D) (4009 Treffer)

Da es sich hierbei um ein PrimoCentral Problem handelt sollten wir dies bzgl. ein Ticket bei ExLibiris aufmachen und um Klärung bitten.

**Comment by msievers** [comment]
@renspr Kannst du bitte ein Ticket bei ExLibris dies bzgl. aufmachen ?

**Comment by renspr** [comment]
Es scheint sich dabei um gewolltes Verhalten zu handeln. Führt man diese Suche in einem primo System durch, erhält man folgende Nachricht:

> Ihre initiale Suche erbrachte nur wenige oder gar keine Ergebnisse. Die unten angezeigten Ergebnisse wurden durch Erweiterung Ihrer Suche gefunden

ExLibris schreibt dazu:
> Full text search is only used if the original search in the metadata yields very few results. In that case, the search is extended to full text and therefore yields additional results. Similarly, we add other expansions for searches with few results.
