### ISSUE TITLE
HTTP 404 für /browserconfig.xml

### ISSUE THREAD

**Issue by msievers** [ubpb/issues#7]
Der IE versucht eine Datei `/browserconfig.xml` aufzurufen. Da diese nicht existiert, führt dies momentan zu unnötigen `404` Fehlern im Log und in Newrelic.

## Ziel
Um die Logs und Newrelic nicht unnötig mit diesen "Fehlern" zu füllen, wäre es wünschenswert, dem IE irgendwie sagen zu können, dass er bitte nicht nach dieser Datei gucken soll, bzw. ihm einen entsprechenden Platzhalter zu servieren.

Auf [Stackoverflow](http://stackoverflow.com/questions/23043429/what-is-a-simple-minimal-browserconfig-xml-for-a-web-site) werden folgende zwei Ansätze vorgeschlagen
* `<meta name="msapplication-config" content="none"/>`
  * funktioniert anscheinend nicht in 100% aller Fälle
* eine Dummy browserconfig.xml

*Beispiel für eine minimale browserconfig.xml*
```xml
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
    </msapplication>
</browserconfig>
```

Ich würde beides implementieren. IEs, welche den Metatag respektieren, sparen sich den Aufruf der XML Datei und alle anderen erhalten die minimale `browserconfig.xml`.

**Comment by msievers** [comment]
Falls keine Einwände bestehen, implementiere ich das wie oben beschrieben. @renspr

**Comment by renspr** [comment]
ok
