### ISSUE TITLE
Bestimmte Signaturen können nicht gefunden werden

### ISSUE THREAD

**Issue by msievers** [ubpb/issues#79]
Es gab eine Meldung, dass die Signatur `PNL3036(8)-1` nicht gefunden werden kann.

[Suche nach PNL3036(8)-1 im Katalog](https://katalog.ub.upb.de/local/searches?search_request=%7B%22queries%22%3A%5B%7B%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_operator%22%3A%22AND%22%2C%22fields%22%3A%5B%22_all%22%5D%2C%22query%22%3A%22PNL3036%288%29-1%22%7D%5D%2C%22sort%22%3A%5B%7B%22field%22%3A%22_score%22%7D%5D%7D)

Eine Suche nach `PNL3036(8)` liefert den Titel zusammen mit einem weiteren Treffer.

[Suche nach PNL3036(8) im Katalog](https://katalog.ub.upb.de/local/searches?search_request=%7B%22queries%22%3A%5B%7B%22exclude%22%3Afalse%2C%22type%22%3A%22query_string%22%2C%22default_operator%22%3A%22AND%22%2C%22fields%22%3A%5B%22_all%22%5D%2C%22query%22%3A%22PNL3036%288%29%22%7D%5D%2C%22sort%22%3A%5B%7B%22field%22%3A%22_score%22%7D%5D%7D)

 Es stellt sich nun die Frage, warum die Singatur mit Bindestrich nicht gefunden wird.

**Comment by msievers** [comment]
Eine Untersuchung der Index-/Searchanalyzer hat ergeben, dass die generierten Tokens im Index nicht mit einem der Tokens überstimmen, welche im Suchfall erzeugt werden.

`default`

```
pnl3036(8)-1 start: 0 end: 12 pos: 0
pnl3036      start: 0 end: 7 pos: 0
pnl303681    start: 0 end: 12 pos: 0
8            start: 8 end: 9 pos: 1
1            start: 11 end: 12 pos: 2
```

`default_search`

```
pnl3036(8)1  start: 0 end: 12 pos: 0
```

**Comment by msievers** [comment]
Eine Lösung bestünde darin, das Verhalten des `default_search` Analyzers dahingehend zu modifizieren, dass die generierten Tokens mit denen des `default` Analyzers übereinstimmen.

**Comment by msievers** [comment]
Die Ergebnisse der Analyzer mit den neuen Einstellungen

`default`

```
pnl3036(8)-1 start: 0 end: 12 pos: 0
pnl3036      start: 0 end: 7 pos: 0
pnl303681    start: 0 end: 12 pos: 0
8            start: 8 end: 9 pos: 1
1            start: 11 end: 12 pos: 2
```

`default_search`

```
pnl303681    start: 0 end: 12 pos: 0
```

**Comment by msievers** [comment]
Momentan wird mit diesen Einstellungen ein Testindex aufgebaut. Sobald dieser zur Verfügung steht, sollten stichprobenartig Suchen durchgeführt werden um das Ergebnis zu verifizieren und Seiteneffekte (möglichst) auszuschließen.

**Comment by msievers** [comment]
Der Testindex ist im ES Cluster als katalog_test gealiased und damit aktueller Index auf `katalog-test` Stichproben haben gezeigt, dass das Problem damit beseitigt wurde und haben außerdem keine nachteiligen Effekte aufgedeckt.

**Comment by msievers** [comment]
@renspr Von meiner Seite aus ist das erledigt. Die Änderungen müsstest du dann bitte entsprechend nach `v3` übernehmen/cherry-picken.

**Comment by renspr** [comment]
Gefixt in index katalog_20160621
