### ISSUE TITLE
Sortierung nach Titel wird durch Groß-/Kleinschreibung beeinflusst

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#80]
![eaggggcj](https://cloud.githubusercontent.com/assets/495000/15246058/865da05c-190a-11e6-8b42-baf7358dfa14.png)
![iebibehg](https://cloud.githubusercontent.com/assets/495000/15246060/895422ae-190a-11e6-8692-3107fc49c642.png)

**Comment by renspr** [comment]
Erneut gemeldet:

"konntest Du da schon was finden? Ich hatte gestern wieder einen Fall: Suche nach "Franz von Lenbach", erster Treffer Großschreibung, keine Sortierung nach Erscheinungsjahr."

**Comment by msievers** [comment]
Die Sortierung nach Titel scheint gefüllt im Augenblick arg im Eimer zu sein. Beispiel

Suche nach `corporate`

![issue_80_001](https://cloud.githubusercontent.com/assets/156371/19925492/797f914c-a0f0-11e6-899a-89409e619742.png)

Ich werde mir die Generierung des Suchtitels mal komplett vornehmen.

**Comment by msievers** [comment]
Can be closed if deployed/index updated.
