### ISSUE TITLE
Bearbeiten einer Notiz führt zum Skriptfehler

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#91]
Gemeldet von HU.

Wenn man bei einer Notiz an einem Titel diese Notiz bearbeitet, kommt es hin und wieder (im Firefox) dazu, dass der Browser einen Skriptfehler meldet. Als Möglichkeit bietet FF dann an das Skript abzubrechen oder zu debuggen.

Das Problem lässt sich nicht sauber reproduzieren, trat bei HU aber schon mehrfach auf.

Hinweis von HU: Titel in Detailansicht öffnen. Dann zu einer Merkliste hinzufügen und anschließend eine Notiz hinzufügen. Dann tritt der Skriptfehler i.d.R. auf. Browser: Firefox.

**Comment by msievers** [comment]
Kireg ich leider nicht reproduziert. Sowohl mit Firefox als auch mit Chrome kein Fehler bei meinen Versuchen.

Wie sollen wir damit weiterverfahren ? @renspr
