### ISSUE TITLE
Selektives Verlängern

### ISSUE THREAD

**Issue by renspr** [ubpb/issues#98]
Es besteht der Wunsch in der Liste "Meine Ausleihen" via Checkboxen eine Auswahl zu verlängern zusätzlich zu einzelne Titel bzw. alle Titel.

**Comment by msievers** [comment]
Solange dem Nutzer die Möglichkeit offen steht, einfach alle ausgeliehenen Medien per Knopfdruck zu verlängern sehe ich persönlich keinen Vorteil darin, die Logik für eine selektive Auswahl/mehrfach Verlängerung für bestimmte Ausleihen zu implementieren.

Es ist anzunehmen, dass ein Benutzer diese Möglichkeit in den seltensten Fälle wahrnehmen wird, wenn er/sie einfach mit einem Knopfdruck alle seine Ausleihen verlängern kann.
